### PR TITLE
Update several npm packages

### PR DESCRIPTION
**Pull request by arkadyan**
Update lodash from version 4.17.20 to version 4.17.21.

Update hosted-git-info from version 2.8.8 to version 2.8.9.

Update optimize-css-assets-webpack-plugin from version 5.0.1 to version 6.0.0.

### CODE REVIEW

**Review by paulswartz — APPROVED** [review]
🍰 should we configure @dependabot for this repo?

**Comment by arkadyan** [comment]
@paulswartz If I'm understanding the settings correctly I think that Dependabot is configured. I actually got these updates from the alerts tab. I think it wasn't able to apply them directly because one of them was a major update, but it's quite possible something about the configuration also needs fixing…

**Comment by paulswartz** [comment]
@arkadyan https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates has the documentation for configuring `dependabot.yml` which will open pull-requests for you.

**Comment by arkadyan** [comment]
@paulswartz Thanks, that's exactly what I was missing. I'll create a new PR with that.

**Pull request merged**
